markdown: rdiscount
baseurl: https://masterminds.github.io/html5-php

navigation:
- text: Docs
  url: https://github.com/Masterminds/html5-php/wiki
- text: API
  url: https://masterminds.github.io/html5-php/api/2.2.0/
- text: Github
  url: https://github.com/Masterminds/html5-php
